### ISSUE TITLE
The Student "Submit an Entry" button no longer works..

### ISSUE THREAD

**Issue by gutow** [OshkoshScholars/uwosh.oshkoshscholars#10]
This button is directing to portal_url/add_submission_in_home_folder.  However the script appears to be portal_url/portal_skins/custom/createsubmission. Note that although a call to this alternative properly gets the student to the new submission form, it throws an error on save.  See error https://oshkoshscholar.brianledwell.com/prefs_error_log_showEntry?id=1461772290.860.345836710034.

**Comment by tkimnguyen** [comment]
I need to add the authentication from plone.protect

**Comment by tkimnguyen** [comment]
Looks like I need to wrap the view with a security manager

**Comment by gutow** [comment]
Maybe.  I do not understand this one.  I thought it worked for us when we were testing from Dempsey, but it does not work now.  See error entry: https://oshkoshscholar.brianledwell.com/prefs_error_log_showEntry?id=1463668648.180.831154113194
