### ISSUE TITLE
need specific instructions for reviewers

### ISSUE THREAD

**Issue by tkimnguyen** [OshkoshScholars/uwosh.oshkoshscholars#13]
Need to write something up to explain how reviewers are supposed to save and pass on their review notes to student? Currently the view template says “please download the file, save it under a new name, mark it up, save it, then upload the new file here again”, or something to that effect. Should reviewers really be adding comments in the Word document? You’d think if they did so it would leave identifying information about who made the comment, and that would not be easy to hide/remove from the student when they’re supposed to look at the reviewer’s comments

**Comment by gutow** [comment]
I've asked how they have handled this in the past, because they did use direct markup in MSWord.  No answer yet.  I suspect they either manually transferred stuff or did not worry about it.

**Comment by gutow** [comment]
I believe this is fixed.

**Comment by tkimnguyen** [comment]
in https://github.com/OshkoshScholars/uwosh.oshkoshscholars/commit/a28c47091b1f9dcf5c3e0cc9c5b31fbe7979a9cf
