### ISSUE TITLE
Reviewers need an active link for the upload of their reviewed document...

### ISSUE THREAD

**Issue by gutow** [OshkoshScholars/uwosh.oshkoshscholars#18]
Instructions for reviewers are now complete, but there is no link  or button for the "upload here" instruction.  This is about line 200 in the [studentsubmissionview.pt](https://github.com/OshkoshScholars/uwosh.oshkoshscholars/blob/master/src/uwosh/oshkoshscholars/browser/templates/studentsubmissionview.pt#L200).

**Comment by gutow** [comment]
Is this the same issue https://github.com/OshkoshScholars/uwosh.oshkoshscholars/issues/16?

**Comment by tkimnguyen** [comment]
Yes, so closing this one.
